#!/bin/bash -xe

brew_items=(
    brew-cask
    go python ruby
    adobe-air-sdk haxe
    android-sdk ant
    docker fig
    fabric ansible
    git git-flow mercurial
    vim nkf jq tmux weechat
    awscli
    ffmpeg imagemagick
    zsh zsh-completions
    googlecl
)

brew_cask_items=(
    dropbox
    google-chrome
    vagrant
    virtualbox
)

main(){
    install_brew

    install_brew_items
    update_brew_items

    install_brew_cask_items
    update_brew_cask_items
}

install_brew(){
    type brew || {
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    }
}

install_brew_items(){
    brew install ${brew_items[@]}
}

update_brew_items(){
    brew update
    brew upgrade
    brew cleanup
    brew doctor
}

install_brew_cask_items(){
    brew-cask install ${brew_cask_items[@]}
}

update_brew_cask_items(){
    brew-cask update
    brew-cask cleanup
    brew-cask doctor
}

${1:-main}
