#!/usr/bin/env bash

set -xue

declare -a dotfiles=()
declare basedir=
basedir=$({ cd "$(dirname "$0")"; pwd; cd; })

dotfiles=(
  .bash_profile
  .bashrc
  .gitconfig
  .inputrc
  .tmux.conf
  .vim
  .textlintrc
)

main() {
  install_dotfiles
}

install_dotfiles() {
  for dotfile in "${dotfiles[@]}"
  do
    echo "${basedir}/${dotfile}"
  done \
    | sed -e "s@${HOME}/@@g" \
    | while read -r dotfile
      do
        ln -sf "${dotfile}" "${HOME}/"
      done

  if [[ -f ~/.tmux.conf.local ]]
  then return
  fi

  case "$(uname)" in
  Darwin)
    cat > ~/.tmux.conf.local <<EOS
bind-key -T copy-mode-vi Enter             send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-j               send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi D                 send-keys -X copy-end-of-line
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi A                 send-keys -X append-selection-and-cancel
EOS
    ;;
  *)
    touch ~/.tmux.conf.local
    ;;
  esac
}

err() {
  local ret=$1

  shift
  echo "$*" >&2
  exit "${ret}"
}

main "$@"
