set bs=2
set list listchars=tab:>\ ,trail:-,nbsp:%,extends:>,precedes:<
set autoindent smartindent cindent
set tabstop=2 shiftwidth=2 softtabstop=0 expandtab smarttab
set number ruler title laststatus=2
set nocursorline nocursorcolumn
set noshowcmd

" Encoding
if &encoding !=? 'utf-8' | let &termencoding = &encoding | end
set encoding=utf-8 fileencoding=utf-8 fileformats=unix,mac,dos
set fileencodings=utf-8,iso-2022-jp-3,euc-jisx0213,cp932,euc-jp,sjis,jis,latin,iso-2022-jp

" Performance
set updatetime=300 timeout timeoutlen=500 ttimeout ttimeoutlen=50 ttyfast nolazyredraw

" Search
set wrapscan incsearch hlsearch magic

" Cache
let $cache = expand('~/.cache/backup')
if !isdirectory($cache) | call mkdir($cache, 'p') | end
set history=1000 viminfo='10,/100,:1000,<10,@10,s10,h,n$cache/.viminfo
set nospell  spellfile=$cache/en.utf-8.add
set swapfile directory=$cache/swap,$cache,/var/tmp/vim,/var/tmp
set nobackup backupdir=$cache/backup,$cache,/var/tmp/vim,/var/tmp
set undofile undolevels=1000 undodir=$cache/undo,$cache,/var/tmp/vim,/var/tmp

" Movement
cnoremap <C-A> <Home>
cnoremap <C-B> <Left>
cnoremap <C-D> <Del>
cnoremap <C-E> <End>
cnoremap <C-F> <Right>

nnoremap j gj
nnoremap k gk
vnoremap < <gv
vnoremap > >gv

nmap <Space> <Leader>
vmap <Space> <Leader>

syntax on

let g:netrw_liststyle = 3

if has('vim_starting')
  set rtp+=~/.cache/plugged/vim-plug
  if !isdirectory(expand('~/.cache/plugged/vim-plug'))
    echo 'install vim-plug...'
    call system('mkdir -p ~/.cache/plugged/vim-plug')
    call system('git clone https://github.com/junegunn/vim-plug.git ~/.cache/plugged/vim-plug/autoload')
  end
endif

call plug#begin('~/.cache/plugged')
  Plug 'junegunn/vim-plug',
        \ {'dir': '~/.cache/plugged/vim-plug/autoload'}

  call map(sort(split(globpath(&runtimepath, 'vimrc.d/*.vim'))), {->[execute('exec "so" v:val')]})
call plug#end()

