if &compatible | set nocompatible | end

let b:plugged = expand('~/.vim/bundle/plugged')
if has('vim_starting')
  set rtp+=~/.vim/conf.d

  if !isdirectory(b:plugged . '/vim-plug')
    echo 'install.. vim-plug'
    call system(join([
          \ 'git', 'clone', '--depth', '999',
          \ 'https://github.com/junegunn/vim-plug.git',
          \ b:plugged . '/vim-plug/autoload'], ' '))
    echo 'installed vim-plug'
  end
  set rtp+=~/.vim/bundle/plugged/vim-plug
end

runt! plugged/_pre/*.vim

call plug#begin(b:plugged)
Plug 'junegunn/vim-plug', {'dir': b:plugged . '/vim-plug/autoload'}
Plug 'Raimondi/delimitMate'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim', {'on': ['Buffers','Lines','Files']}
Plug 'haya14busa/vim-auto-programming'
set completefunc=autoprogramming#complete
runt! plugged/*.vim
call plug#end()

runt! plugged/_post/*.vim
unl b:plugged
