#!/bin/bash

__create(){
  while true
  do
    case $1 in
    --name|-n)
      name=$2
      shift 2 || break
      ;;
    role*)
      tasks=(${tasks} $1)
      shift || break
      ;;
    *)
      break
      ;;
    esac
  done

  for task in ${tasks[@]}
  do
    case ${task} in
    role*)
      [[ -z ${name} ]] && exit 1
      mkdir -p ${name}/{tasks,defaults,handlers,meta,templates,files,vars}
      echo created: ${name}/{tasks,defaults,handlers,meta,templates,files,vars}
      ;;
    *)
      break
      ;;
    esac
  done
}

__main(){
  while true
  do
    case $1 in
    c|create)
      shift || break
      __create $@
      ;;

    p|play)
      shift || break
      while [[ ! -z $1 ]]
      do
        case $1 in
        -F)
          export ANSIBLE_SSH_ARGS="-F $2"
          shift 2 || break
          ;;
        *)
          args="${args} $1"
          shift || break
          ;;
        esac
      done
      ansible-playbook -c ssh ${args}
      break
      ;;

    *)
      break
      ;;
    esac
  done
}

__main $@
