#!/bin/bash -e

ps=0
psmax=16
files=()

while true
do
  case "$1" in
  --max*|-m)
    psmax=$2
    shift 2 || break
    ;;

  --comm*|-c)
    cmd=$2
    shift 2 || break
    ;;

  *)
    files=(${files[@]} $1)
    shift || break
    ;;
  esac
done

if [ -z ${files[@]} ]; then
  cat <&0
else
  cat ${files[@]}
fi | while read line
  do
    {
      echo "[${ps}::start] ${cmd} ${line}" >&2
      if [[ -z ${cmd} ]]
      then ${line}
      else ${cmd} "${line}"
      fi
      echo "[${ps}::ended] ${cmd} ${line}" >&2
    } &
    ps=$((${ps} + 1))
    [[ $((${ps} % ${psmax})) -eq 0 ]] && wait && ps=0
  done | cat
