#!/usr/bin/env ruby
require "optparse"

opts = ARGV.getopts "m:s:w:b:",
  "max:100",   "size:5",
  "boxes: -=", "box-width:1"

max     = (opts["m"] || opts["max"]).to_i
size    = (opts["s"] || opts["size"]).to_i
width   = (opts["w"] || opts["box-width"]).to_i
boxes   = (opts["b"] || opts["boxes"]).scan /.{1,#{width}}/

first = true
prev_text = ""

while line = gets
  raw_value = line.to_f

  value = if max < raw_value then max else raw_value end

  period      = max.to_f / size
  full_boxes  = (value / period).floor
  last_value  = value - full_boxes * period
  last_state  = (last_value * (boxes.size - 1) / period).floor
  empty_boxes = size - full_boxes - (last_value > 0 ? 1 : 0)

  res = []
  res << "\r" unless first
  res << boxes[-1] * full_boxes if full_boxes  > 0
  res << boxes[last_state]      if last_value  > 0
  res << boxes[0] * empty_boxes if empty_boxes > 0
  text = res.join ""
  first = false if first

  next if prev_text == text
  print text
  prev_text = text
end
puts
