#!/bin/bash

# Aliases
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
case ${OSTYPE} in
darwin*)
    alias ls="ls -G"
    export LSCOLORS=gxfxcxdxbxegedabagacad
    ;;
*)
    case ${TERM} in
    "emacs")
        export LS_COLORS="no=00:fi=00:di=35:ln=36:ex=32"
        export TERM_LENGTH="90"
        alias ls="ls --classify --color --show-control-char -C"
        ;;
    *)
        stty -ixon -ixoff
        eval $(dircolors ~/.dir_colors)
        alias ls="ls --classify --color=auto --show-control-char"
        alias ls='ls -hF --color=tty' # classify files in colour
        ;;
    esac
    ;;
esac

function pushd_func {
    if [ -z "$*" ]
        then cd ~
        else pushd "$*" > /dev/null
    fi
}

function popd_func {
    popd "$*" > /dev/null
}

alias less='less -rN'                         # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #
alias mkdir='mkdir -p'
alias df='df -h'
alias du='du -h'
alias cd=pushd_func
alias pd=popd_func
alias dirs='dirs -v | awk "!uniq[\$2]{uniq[\$2]=1;print \$0}" | sort -k 2'
alias lmake='make -f ~/.Makefile'
alias ansible-playbook='ANSIBLE_SSH_ARGS="-F $HOME/.ssh/config" ansible-playbook -c ssh'

aliasf(){ alias | sed -e "s/^\([^=]*\)=\(.*\)/\1 => \2/" -e "s/'//g" | grep $* --color ; }
