#!/bin/bash

# [history]
function __share_history {
    history -a
    history -r
}

case $SHELL in
    *bash)
        shopt -u histappend
        export HISTSIZE=9999
        # コマンド入力時間を記録
        export HISTTIMEFORMAT='%y/%m/%d %H:%M:%S  '
        # historyに記録しないコマンド
        export HISTIGNORE=ls:la:ll:lla:history:pwd:cd*
        export HISTCONTROL=ignoredups:ignorespace:erasedups
    ;;
esac

# [prompt]
function custom_prompt {
    prompt_result=$?

    __share_history

    PS1="\[\e[0;00m\]\[\e[1;30m\]$ssh_prompt
$name_color\u\[\e[0;37m\]@\[\e[0;32m\]\h \[\e[0;33m\]\w \[\e[0;37m\]\t $(__stat_ps1)
\[\e[0;31m\]$(__git_ps1)\[\e[0;37m\]\$ \[\e[0;00m\]"
}

PROMPT_COMMAND='custom_prompt'

function __git_ps1 {
    [[ ! -z $NO_PROMPT_GIT ]] && return

    git_diff=$([[ -z $(git status --short 2> /dev/null) ]] || echo " *")
    git_branch=$(git branch --no-color 2> /dev/null | awk '/^\*/{print$2}')
    [[ ! -z $git_branch ]] && echo "($git_branch$git_diff) "
}

function __stat_ps1 {
    [[ 0 -eq $prompt_result ]] && echo "\[\e[0;32m\][$prompt_result] " || echo "\[\e[0;31m\][$prompt_result] "
}

name_color=$([[ -z "$SSH_CLIENT" ]] && echo "\[\e[0;36m\]" || echo "\[\e[0;35m\]")
ssh_prompt=$(echo $SSH_CLIENT | awk '$1!=""{printf "From: %s\n", $1}')
