#!/bin/bash

# ------------------------------------
# Docker alias and function
# ------------------------------------

alias dbuild='docker build'

alias dexec='docker exec'

alias dimages='docker images'

alias dkill='docker kill'

alias dlogs='docker logs'

alias dps='docker ps'

alias dpull='docker pull'

alias dpush='docker push'

alias drm='docker rm'

alias drmi='docker rmi'

alias drun='docker run'

alias dstart='docker start'

alias dstop='docker stop'

alias dtag='docker tag'

alias dtop='docker top'

alias dip='docker ps -q | xargs docker inspect --format "{{.Id}} {{.NetworkSettings.IPAddress}}"'

dclean(){
    docker ps -aq | xargs docker rm 2>/dev/null
    docker images | awk '/<none>/{print$3}' | xargs docker rmi 2>/dev/null
}
