#!/bin/bash

function echoR {
    echo -e "\e[31m$*\e[m"
}

function echoG {
    echo -e "\e[32m$*\e[m"
}

function echoY {
    echo -e "\e[33m$*\e[m"
}

render_template () {
    eval "echo \"`cat $1`\""
}

render_templates () {
    for tmpl in `find $* -type f -name *.tmpl`
    do
        tmpl_result=${tmpl%.tmpl}
        [[ -f $tmpl_result ]] &&
           echoY "already exists: $tmpl_result"

        echo -n "rendering... $tmpl: "
        render_template $tmpl > $tmpl_result &&
            echoG "success" ||
            echoR "error"
    done
}

daemon_exec() {
    local pid_file=/dev/null
    local log_file=/dev/null
    local args=""

    while [[ ! -z "$1" ]]
    do case "$1" in
    --log_file) log_file=$2
    shift 2 || return 1 ;;

    --pid_file) pid_file=$2
    shift 2 || return 1 ;;

    *) args="$args '$1'"
    shift || break ;;
    esac
    done

    sh -c "$args" >> $log_file & echo $! > $pid_file
}
