#!/bin/bash

function echoR {
    echo -e "\e[31m$*\e[m"
}

function echoG {
    echo -e "\e[32m$*\e[m"
}

function echoY {
    echo -e "\e[33m$*\e[m"
}

function render_template {
    eval "echo \"`cat $1`\""
}

function render_templates {
    for tmpl in `find $* -type f -name *.tmpl`
    do
        tmpl_result=${tmpl%.tmpl}
        [[ -f $tmpl_result ]] &&
           echoY "already exists: $tmpl_result"

        echo -n "rendering... $tmpl: "
        render_template $tmpl > $tmpl_result &&
            echoG "success" ||
            echoR "error"
    done
}
