#!/usr/bin/env bash

set -xue

apt-get install --no-install-recommends \
  vim \
  vim-gtk3 \
  xclip \
  gnome-shell-pomodoro \
  keepassxc \
  mpv \
  fcitx-mozc \
  fonts-noto-cjk \
  fonts-noto-mono

for src in \
  https://github.com/eosrei/twemoji-color-font/releases/download/v12.0.1/fonts-twemoji-svginot_12.0.1-1_all.deb \
  https://github.com/alacritty/alacritty/releases/download/v0.4.1/Alacritty-v0.4.1-ubuntu_18_04_amd64.deb
do
  if [[ ! -f "/tmp/$(basename $src)" ]]
  then curl -sSL ${src} -o "/tmp/$(basename $src)"
  fi

  apt-get install --no-install-recommends "/tmp/$(basename $src)"
done

curl -sSL https://download.docker.com/linux/debian/gpg | apt-key add -

echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list

apt-get update
apt-get install docker-ce docker-ce-cli containerd.io

echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -cs) main" \
  > /etc/apt/sources.list.d/google-cloud-sdk.list

curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

apt-get update
apt-get install google-cloud-sdk
