#!/usr/bin/env bash

set -xue

apt-get install --no-install-recommends \
  build-essential \
  ca-certificates \
  curl \
  gnupg-agent \
  lsb-release \
  apt-transport-https \
  software-properties-common

aptpkgs=()

aptpkg(){
  while [[ $# -gt 0 ]]
  do
    case $1 in
      https://*)
        if [[ ! -f "/tmp/$(basename "$1")" ]]
        then curl -sSL "$1" -o "/tmp/$(basename "$1")"
        fi

        aptpkgs=("${aptpkgs[@]}" "/tmp/$(basename "$1")")
        ;;
      *)
        aptpkgs=("${aptpkgs[@]}" "$1")
        ;;
    esac
    shift
  done
}

aptpkg_repo(){
  while [[ $# -gt 0 ]]
  do
    case $1 in
      --name=*)
        reponame="${1#*=}"
        ;;
      --source=*)
        reposrc="${1#*=}"
        ;;
      --key=https://*)
        keyurl="${1#*=}"
        curl -sSL "${keyurl}" | apt-key add -
        ;;
    esac
    shift
  done
  echo "${reposrc}" > "/etc/apt/sources.list.d/${reponame}.list"
}

aptpkg julia
aptpkg clang clang-tools
aptpkg vim vim-gtk3
aptpkg xclip
aptpkg gnome-shell-pomodoro
aptpkg keepassxc
aptpkg mpv
aptpkg fcitx fcitx-mozc
aptpkg fonts-noto-cjk fonts-noto-mono

aptpkg_repo \
  --name=docker \
  --key=https://download.docker.com/linux/debian/gpg \
  --source="deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

aptpkg docker-ce docker-ce-cli containerd.io

aptpkg_repo \
  --name=cloud-sdk \
  --key=https://packages.cloud.google.com/apt/doc/apt-key.gpg \
  --source="deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -cs) main"

aptpkg google-cloud-sdk

apt-get update
apt-get install --no-install-recommends "${aptpkgs[@]}"

gpasswd --add "${USER}" docker

# install snapd
apt-get install libsquashfuse0 squashfuse fuse snapd
