#!/usr/bin/env bash

set -xue

declare -a dotfiles=()
declare basedir=
basedir=$(cd "$(dirname "$0")/.."; pwd)

dotfiles=(
  .bashrc.include
  .gitconfig
  .gitignore.global
  .inputrc
  .tmux.conf
  .vim
  .textlintrc
)

main() {
  install_dotfiles
}

install_dotfiles() {
  for dotfile in "${dotfiles[@]}"
  do
    echo "${basedir}/${dotfile}"
  done \
    | sed -e "s@${HOME}/@@g" \
    | while read -r dotfile
      do
        ln -sf "${dotfile}" "${HOME}/"
      done

  mkdir -p "${HOME}/.config"
  for config in $(find "${basedir}/.config/" -maxdepth 1 | sed -e "s@${HOME}/@../@")
  do cp -rv "${config}" "${HOME}/.config/"
  done

  if [[ -f ~/.tmux.conf.local ]]
  then return
  fi

  case "$(uname)" in
  Darwin)
    cat > ~/.tmux.conf.local <<EOS
bind-key -T copy-mode-vi v                 send      -X begin-selection
bind-key -T copy-mode-vi y                 send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter             send-keys -X copy-pipe-and-cancel "pbcopy"
EOS
    ;;
  *)
    touch ~/.tmux.conf.local
    ;;
  esac
}

err() {
  local ret=$1

  shift
  echo "$*" >&2
  exit "${ret}"
}

main "$@"
