#!/usr/bin/env bash

set -xue
gotools=(
   github.com/ddollar/forego
   github.com/mattn/memo
   github.com/saibing/bingo
   github.com/sclevine/yj
   golang.org/x/tools/cmd/goyacc
)

GO111MODULE=on go get -v "${gotools[@]}"
