#!/usr/bin/env bash

set -xue
gotools=(
   github.com/ddollar/forego
   github.com/motemen/gore/cmd/gore
   github.com/mattn/memo@master
   github.com/saibing/bingo
   github.com/sclevine/yj
   golang.org/x/tools/cmd/goyacc
   honnef.co/go/tools/staticcheck
)

for t in "${gotools[@]}"
do GO111MODULE=on go get -v "${t[@]}"
done
