#!/usr/bin/env bash

set -xue
gotools=(
   github.com/cweill/gotests/gotests@master
   github.com/ddollar/forego
   github.com/dominikh/go-tools/cmd/staticcheck
   github.com/golangci/golangci-lint/cmd/golangci-lint
   github.com/mattn/memo@master
   github.com/motemen/gore/cmd/gore
   github.com/sclevine/yj
)

cd "$(dirname "$0")"
GO111MODULE=on go get -v "${gotools[@]}"
GO111MODULE=on go get -v golang.org/x/tools/cmd/...
