#!/usr/bin/env bash

set -xue
gotools=(
   github.com/cweill/gotests/gotests
   github.com/ddollar/forego
   github.com/golangci/golangci-lint/cmd/golangci-lint
   github.com/mattn/memo
   github.com/motemen/gore/cmd/gore
   github.com/sclevine/yj
)

cd "$(dirname "$0")"
GO111MODULE=off go get -u -v "${gotools[@]}"
GO111MODULE=off go get -u -v golang.org/x/tools/cmd/...
